Hometask_1.ipynb
ChernykhAA/autumn2020 pull request #1
Opened 2020-09-19 11:52 UTC by ChernykhAA

2020-09-20 16:58 UTC, illarionovEA requested changes
проверять нечего

2020-09-20 17:32 UTC, ChernykhAA commented
файл Hometask_1.ipynb в ветке master

2020-09-21 06:24 UTC, ChernykhAA commented
тот же самый файл, но теперь Files changed 1

2020-09-21 16:56 UTC, illarionovEA approved these changes

2020-09-22 15:18 UTC, merged